name: Continuous integration
on:
  pull_request:
  push:
    branches:
    - main
defaults:
  run:
    shell: bash
jobs:
  ci-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - if: ${{ github.event_name == 'push' }}
      uses: docker/login-action@v3
      with:
        username: stephanmisc
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: stepchowfun/toast/.github/actions/toast@main
      with:
        tasks: build-main build-example lint
        docker_repo: stephanmisc/toast
        read_remote_cache: true
        write_remote_cache: ${{ github.event_name == 'push' }}